// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6964.FRCBearBots.subsystems;

import org.usfirst.frc6964.FRCBearBots.RobotMap;
import org.usfirst.frc6964.FRCBearBots.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveSystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController speedController1 = RobotMap.driveSystemSpeedController1;
    private final SpeedController speedController2 = RobotMap.driveSystemSpeedController2;
    private final SpeedControllerGroup speedControllerGroup1 = RobotMap.driveSystemSpeedControllerGroup1;
    private final SpeedController speedController3 = RobotMap.driveSystemSpeedController3;
    private final SpeedController speedController4 = RobotMap.driveSystemSpeedController4;
    private final SpeedControllerGroup speedControllerGroup2 = RobotMap.driveSystemSpeedControllerGroup2;
    private final DifferentialDrive differentialDrive1 = RobotMap.driveSystemDifferentialDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    int sensitivity = 1;
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new TeleopArcadeDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    public void takeJoystickInputs(Joystick leftJoystick, Joystick rightJoystick) {
//    	robotDrive.arcadeDrive(joystick.getY(), joystick.getX()); //For one
    	differentialDrive1.tankDrive(leftJoystick.getY(), rightJoystick.getY()); //For two
    }
    
    public void takeJoystickInput(Joystick joystick) {
    	differentialDrive1.arcadeDrive(joystick.getY(), joystick.getX());
    }
    
    public void takeXJoystickAxisOnly(Joystick joystick) {
    	differentialDrive1.arcadeDrive(0, joystick.getX()/2);
    }
    
    public void takeThrottle(Joystick joystick) {
//    	sensitivity = (int) joystick.getThrottle();
    	System.out.println(joystick.getThrottle());
    }
    
//    public void  stop() {/ M9 i've not a clue
//    	robotDrive.drive(0, 0);
//    }
    
    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

